sudo: required
dist: xenial
language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - sudo apt-get install -y libxcb1 xvfb libxkbcommon-x11-0

install:
  - python pft.py --install_qt

script:
  - xvfb-run python tests.py

