sudo: required
dist: xenial
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

before_install:
  - sudo apt-get install -y libxcb1 xvfb libxkbcommon-x11-0

install:
  - pip install PySide2==5.12.1

script:
  - xvfb-run python tests.py

