environment:
    matrix:
        - PYTHON: "C:\\Python35-x64"

        - PYTHON: "C:\\Python36-x64"

        - PYTHON: "C:\\Python37-x64"

        - PYTHON: "C:\\Python38-x64"
          PYTHON_VERSION: "3.8.1"

install:
    - "%PYTHON%\\python.exe pft.py --install_qt"

build: off

test_script:
    - "%PYTHON%\\python.exe tests.py"

