environment:
    matrix:
        - PYTHON: "C:\\Python35-x64"
          PYTHON_VERSION: "3.5"

        - PYTHON: "C:\\Python36-x64"
          PYTHON_VERSION: "3.6"

        - PYTHON: "C:\\Python37-x64"
          PYTHON_VERSION: "3.7"

        - PYTHON: "C:\\Python38-x64"
          PYTHON_VERSION: "3.8"

    #Pyside doesn't work on 3.8.0: https://bugreports.qt.io/browse/PYSIDE-1166
    allow_failures:
        - PYTHON_VERSION: "3.8"

install:
    - "%PYTHON%\\python.exe pft.py --install_qt"

build: off

test_script:
    - "%PYTHON%\\python.exe tests.py"

