on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ['3.11']
    name: Python ${{ matrix.python-version }} Windows build
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install pyinstaller==6.1.0
      - run: pyinstaller --onefile bricbooks.py
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
            name: bricbooks.exe
            path: dist/bricbooks.exe
