on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
    name: Python ${{ matrix.python-version }} Linux tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: sudo apt-get install -y libxcb1 xvfb libxkbcommon-x11-0 libxcb-icccm4
      - run: python bricbooks.py --install_qt
      - run: QT_DEBUG_PLUGINS=1 xvfb-run python tests.py

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    name: Python ${{ matrix.python-version }} Windows tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python bricbooks.py --install_qt
      - run: python tests.py

  mac:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    name: Python ${{ matrix.python-version }} Macos tests
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: python bricbooks.py --install_qt
      - run: python tests.py
